POST http://localhost:6000/dev/orders/place http/1.1
Content-Type: application/json

{
    "cust_id": 1,
    "items": [
        {
            "product_id": 1,
            "quantity": 1,
            "price": 12.99,
            "discount": 0.12
        },
        {
            "product_id": 2,
            "quantity": 1,
            "price": 9.99,
            "discount": 0.05
        },
        {
            "product_id": 7,
            "quantity": 1,
            "price": 30.00,
            "discount": 1
        }
    ]
}